name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_node_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.5.0 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: npx prisma migrate dev
      - run: npm test
