name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm install
    - uses: ankane/setup-postgres@v1
      with:
        database: pgvector_node_test
    - run: |
        sudo apt-get update && sudo apt-get install postgresql-server-dev-13
        git clone --branch v0.1.7 https://github.com/ankane/pgvector.git
        cd pgvector
        make
        sudo make install
    - run: npm test
